### ISSUE TITLE
Web client: upload file from local filesystem

### ISSUE THREAD

**Issue by orogenic** [anguyen120/mabcs#1]
Implement a Web client mechanism for the user to upload a file from their local filesystem. There is no backend yet, so you do not need to implement the file transfer.

The backend must store the file binary data and the file type. The client MUST send the file binary data, and may optionally send metadata such as a filename or a file type. 

The client may detect the file type from the file binary data or filename, or may make the server detect the file type.

Methods for detection include
1) system built-in routines
2) implement parsing the file header from the file binary data
3) implement parsing the file extension from the filename
4) implement prompting the user to select the file type from a dropdown of supported file types (not recommended but quick)

The file type may be encoded as any suitable standardized type format (such as a MIME type string), or a custom type format

The system must support at least PDF and JPEG, for now.

Considered use cases include
1) uploading the receipt file (normally a PDF or JPEG image) for a transaction

**Comment by jonathan-mejia-deluna** [comment]
Since there's no backend code to handle file uploads, for now, I'm just opening the user-uploaded file in another tab. The file is stored as a JavaScript File object which is defined in the else statement in the function **uploadButtonHandler**. Y'all let me know if there's anything y'all don't like about it or something y'all want me to add.

**Comment by jonathan-mejia-deluna** [comment]
Do y'all think it makes sense to restrict the file type the user may upload?
